### ISSUE TITLE
02 - DESIGN - Implementação da autenticação passwordless

### ISSUE THREAD

**Issue by renansap** [Painel-Solidario-RS/Painel-Solidario-RS#12]
Desenvolva a lógica para permitir que os usuários se autentiquem utilizando e-mail e código único.
 - [x] Design da página de login: Criar o layout e o design da página de login, garantindo que seja intuitiva e fácil de usar.

**Comment by carla-reis-cr** [comment]
<img width="2908" alt="1 1 Fluxo de Login" src="https://github.com/Painel-Solidario-RS/Painel-Solidario-RS/assets/47834995/cc5a1a12-d3c5-4871-83e4-2ae8dc8724bb">

Definições no Figma

**Comment by rodrigok** [comment]
@carla-reis-cr essas telas não estão compreendendo o fluxo sem senha, seria preciso mudar a tela para pedir apenas o email, fazer o design do email com o código ou link (dependo do que decidirem de fluxo).

**Comment by rodrigok** [comment]
@carla-reis-cr exemplo https://www.loom.com/share/2e1393b680584cc8b89765bb310aafb9?sid=27ac5397-d2c6-44b1-bd9e-474d6b7e91f1
