### ISSUE TITLE
02.02 - BACK - Implementação da autenticação passwordless

### ISSUE THREAD

**Issue by renansap** [Painel-Solidario-RS/Painel-Solidario-RS#14]
Desenvolva a lógica para permitir que os usuários se autentiquem utilizando e-mail e código único.
 - [ ] Configuração do serviço de e-mail: Configurar o serviço de e-mail para enviar os códigos únicos de autenticação aos usuários.
 - [ ] Desenvolvimento da lógica de autenticação: Implementar a lógica no back-end para processar os códigos únicos enviados pelos usuários e autenticá-los.
 - [ ] Gestão de usuários: Desenvolver a lógica para criar, atualizar e excluir contas de usuários, além de gerenciar as informações de perfil.
 - [ ] Segurança: Implementar medidas de segurança, como criptografia de dados e prevenção contra ataques de força bruta.!!!

**Comment by joaovperin** [comment]
Fluxo: 
Usuário digital o e-mail e clica em login, em seguida receberá no e-mail um código de uso único para realizar o login.

Será necessário um endpoint para geração do código a partir do e-mail e outro que recebe um e-mail e um código, e realiza sua validação.

O código OTP gerado deverá ser armazenado no banco de dados e conter um campo com sua data de validade. Acho que podemos fazer uma duração de 30 minutos para que o token possa ser usado.

No Endpoint de validação do token, o mesmo deverá ser consumido (deletado do banco de dados) para evitar reuso.

Também é interessante possuir uma rotina para busca e deleção de tokens expirados do banco de dados, a fim de evitar armazenamento de dados desnecessários. Essa rotina pode ser exposta via endpoint e chamada de forma manual ou via tarefa agendada posteriormente, conforme necessidade.

Endpoints:
`POST /generate-access-token {email}`
`POST /validate-access-token {email, token}`
`DELETE /expired-access-tokens`

Estrutura: `Token {userId, token, expirationDate}`.

Para a prevenção de ataques de força bruta, podemos implementar um recurso chamado de [Rate Limiting](https://www.cloudflare.com/pt-br/learning/bots/what-is-rate-limiting/), . É importante não só no login mas em toda a aplicação, então acho que isso merece uma task separada para analisarmos melhor e realizar a implementação adequada. Para o escopo desta tarefa, a adoção de um código de `6 dígitos alfanuméricos` com `30 minutos` de duração já é suficiente.

**Comment by renansap** [comment]
@jonas-duarte conseguiste fazer um tópico no DS para podermos discutir?

@rodrigok consegue nos apoiar nesta demanda?

**Comment by rodrigok** [comment]
Eu sugiro o envio de um link de autenticação ao invés do código, é mais simples e rápido, mas o código funciona também.

Se for usado JWT para tokens de acesso, não é necessário um endpoint ou rotina para remoção dos tokens antigos, caso contrário, o processo de login pode fazer uma segunda chamada para remover tokens velhos. No mongodb existe uma função de TTL, não sei se isso é possível no postgres para auto deletar registros.
