### ISSUE TITLE
03.02 - BACK - Desenvolvimento do cadastro de abrigos

### ISSUE THREAD

**Issue by renansap** [Painel-Solidario-RS/Painel-Solidario-RS#15]
Funcionalidades para permitir que abrigos se cadastrem na plataforma, incluindo a inserção e atualização de informações.

 - [ ] Configuração do banco de dados: Criar e configurar o banco de dados para armazenar as informações dos abrigos.
 - [ ] Desenvolvimento da lógica de cadastro: Implementar a lógica no back-end para processar e armazenar os dados enviados pelo formulário de cadastro.
 - [ ] Implementação da lógica de validação: Desenvolver a lógica para validar os dados enviados pelos abrigos e garantir sua integridade.

**Comment by GustavoASC** [comment]
O backend para cadastrar abrigos (shelter) já foi implementado [nesse PR](https://github.com/Painel-Solidario-RS/backend/pull/34), então não precisamos mais dessa tarefa.
