### ISSUE TITLE
05 - DESIGN - Desenvolvimento do cadastro de pessoas

### ISSUE THREAD

**Issue by renansap** [Painel-Solidario-RS/Painel-Solidario-RS#17]
Implemente as funcionalidades para permitir que pessoas se cadastrem na plataforma e forneçam informações sobre suas habilidades e disponibilidade.

 - [x] Design da página de cadastro de voluntários: Criar o layout e o design da página de cadastro de voluntários, garantindo que seja intuitiva e fácil de usar.

**Comment by carla-reis-cr** [comment]
<img width="1703" alt="1.2 Fluxo de Cadastro de usuário" src="https://github.com/Painel-Solidario-RS/Painel-Solidario-RS/assets/47834995/0ed53fba-9fb1-4b72-ba19-09c1b0cc2334">

Maiores definições no Figma
