### ISSUE TITLE
03 - DESIGN - Desenvolvimento do cadastro de abrigos

### ISSUE THREAD

**Issue by renansap** [Painel-Solidario-RS/Painel-Solidario-RS#20]
Funcionalidades para permitir que abrigos se cadastrem na plataforma, incluindo a inserção e atualização de informações.
 - [x] Design da página de cadastro de abrigos: Criar o layout e o design da página de cadastro, garantindo que seja intuitiva e fácil de usar.

**Comment by carla-reis-cr** [comment]
<img width="1165" alt="1 3 Fluxo de Cadastro de abrigo" src="https://github.com/Painel-Solidario-RS/Painel-Solidario-RS/assets/47834995/33a36599-ea03-483f-a755-099760654329">

Definições no Figma
