### ISSUE TITLE
04 - DESIGN - Desenvolvimento do gerenciamento de necessidades

### ISSUE THREAD

**Issue by renansap** [Painel-Solidario-RS/Painel-Solidario-RS#21]
Crie a lógica para permitir que abrigos listem suas necessidades e que doadores visualizem e atendam a essas demandas.

 - [x] Design da página de cadastro de necessidades: Criar o layout e o design da página de cadastro de necessidades dos abrigos, garantindo que seja intuitiva e fácil de usar.

**Comment by carla-reis-cr** [comment]
<img width="1196" alt="1 4 Fluxo de Cadastro de necessidade" src="https://github.com/Painel-Solidario-RS/Painel-Solidario-RS/assets/47834995/4bba2990-d140-46a8-bf6c-3eb7b67d6d71">

Definições no Figma
