### ISSUE TITLE
Refactor components Input

### ISSUE THREAD

**Issue by carla-reis-cr** [Painel-Solidario-RS/Painel-Solidario-RS#39]
Conforme sugestão no PR da issue #25
- [x] Criar componente em `components/ButtonInput/ButtonInput.tsx` migrando a lógica do bloco `type == 'button' ` do arquivo `components/Input/Input.tsx` Dica: pode ser copiado o components Input.tsx e removido lógicas desnecessárias
- [x] Buscar no `src` o uso o componente `Input` e substituir pelo novo quando   `type = 'button' 

_Originally posted by @guimaraespedro in https://github.com/Painel-Solidario-RS/Painel-Solidario-RS/pull/25#discussion_r1607470606_

**Comment by carla-reis-cr** [comment]
- [ ] Criar componente em `components/ButtonInput/ButtonInput.tsx` migrando a lógica do bloco `type == 'button' ` do arquivo `components/Input/Input.tsx` Dica: pode ser copiado o components Input.tsx e removido lógicas desnecessárias
- [ ] Buscar no `src` o uso o componente `Input` e substituir pelo novo quando   `type = 'button'

**Comment by jonas-duarte** [comment]
O ideal é criar dois componentes, o `Button` e o `Input`. Não tem motivo para os dois ficarem no mesmo arquivo.

Teriam que ter os seguintes componentes:
`Button`
`Input`
`Select`
`TextArea` (multiline, para textos maiores)

Cada um em um arquivo separado.
